ci: publish custom branch container images

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1549,6 +1549,8 @@ runs:
         # Source repository (picked from action name)
         METRICS_SOURCE=$(echo $METRICS_ACTION | sed -E 's/metrics.*?$//g' | sed -E 's/_//g')
         echo "Source: $METRICS_SOURCE"
+        echo "Action repository: $METRICS_ACTION_REPOSITORY"
+        echo "Action ref: $METRICS_ACTION_REF"
 
         # Version (picked from package.json)
         METRICS_VERSION=$(grep -Po '(?<="version": ").*(?=")' package.json)
@@ -1559,8 +1561,16 @@ runs:
         echo "Image tag: $METRICS_TAG"
 
         # Image name
+        # Custom pre-built action
+        if [[ $METRICS_ACTION_REPOSITORY == "AjmalShajahan/metrics" ]] && [[ $METRICS_ACTION_REF =~ ^custom(-test)?$ ]] && [[ ! $METRICS_USE_PREBUILT_IMAGE =~ ^([Ff]alse|[Oo]ff|[Nn]o|0)$ ]]; then
+          METRICS_IMAGE="ghcr.io/ajmalshajahan/metrics:$METRICS_ACTION_REF"
+          echo "Using custom pre-built image $METRICS_IMAGE"
+          if ! docker image pull $METRICS_IMAGE; then
+            echo "Failed to fetch custom image from GitHub registry, will rebuild it locally"
+            METRICS_IMAGE=metrics:forked-$METRICS_VERSION
+          fi
         # Official action
-        if [[ $METRICS_SOURCE == "gh-metrics" ]]; then
+        elif [[ $METRICS_SOURCE == "gh-metrics" ]]; then
           # Use registry with pre-built images
           if [[ ! $METRICS_USE_PREBUILT_IMAGE =~ ^([Ff]alse|[Oo]ff|[Nn]o|0)$ ]]; then
             # Is released version
@@ -1610,6 +1620,8 @@ runs:
       env:
         METRICS_ACTION: ${{ github.action }}
         METRICS_ACTION_PATH: ${{ github.action_path }}
+        METRICS_ACTION_REPOSITORY: ${{ github.action_repository }}
+        METRICS_ACTION_REF: ${{ github.action_ref }}
         METRICS_USE_PREBUILT_IMAGE: ${{ inputs.use_prebuilt_image }}
         INPUTS: ${{ toJson(inputs) }}
         TZ: ${{ inputs.config_timezone }}
